upload-documentation-job:
  stage: deploy
  image: node:16
  script:
    - npx -y rdme@7.4.0 docs ./docs --key=${README_API_KEY} --version=v1.0-dev
    - npx -y rdme@7.4.0 docs ./docs2 --key=${README_API_KEY_INTERNAL} --version=v1-dev
  only:
    - main
